[build]
builder = "NIXPACKS"
buildCommand = "cd pc-deals-backend && mvn clean package -DskipTests"

[deploy]
startCommand = "cd pc-deals-backend && java -jar target/*.jar"
restartPolicyType = "ON_FAILURE" 